package mapper;

import org.apache.ibatis.annotations.Mapper;

import model.Sys_user;


@Mapper
public interface Sys_userMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Tue Jun 25 10:14:28 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Tue Jun 25 10:14:28 CST 2019
     */
    int insert(Sys_user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Tue Jun 25 10:14:28 CST 2019
     */
    int insertSelective(Sys_user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Tue Jun 25 10:14:28 CST 2019
     */
    Sys_user selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Tue Jun 25 10:14:28 CST 2019
     */
    int updateByPrimaryKeySelective(Sys_user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Tue Jun 25 10:14:28 CST 2019
     */
    int updateByPrimaryKey(Sys_user record);
}